name: Build

on:
  pull_request:
    branches: [main]
  workflow_call:

jobs:
  build:
    runs-on: "ubuntu-latest"
    env:
      HUGO_VERSION: 0.123.0
    steps:
      - uses: actions/checkout@v4

      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Install Node.js dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Archive app artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: |
            spin.toml
            modules/
            public/