name: Deploy Website

on:
  push:
    branches:
      # TODO: rm after testing
      - feat/spin-based-deploy
      - main

  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: app
          path: "${{ github.workspace }}"

      - name: Setup `spin`
        uses: fermyon/actions/spin/setup@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Fermyon Cloud
        uses: fermyon/actions/spin/deploy@v1
        with:
          run_build: false
          fermyon_token: "${{ secrets.FERMYON_CLOUD_TOKEN }}"
